OLED.init(128, 64)
OLED.write_string_new_line("*********************")
OLED.write_string_new_line("******    ****   ****")
OLED.write_string_new_line("*********************")
OLED.write_string_new_line("*******        ******")
OLED.write_string_new_line("***********  ********")
OLED.write_string_new_line("*********************")
