OLED.init(128, 64)
OLED.writeStringNewLine("*********************")
OLED.writeStringNewLine("******    ****   ****")
OLED.writeStringNewLine("*********************")
OLED.writeStringNewLine("*******        ******")
OLED.writeStringNewLine("***********  ********")
OLED.writeStringNewLine("*********************")
